server:
  port: 8093
spring:
  profile: local
  mail:
    username: ismaeltesttrocha@gmail.com
    password: pxfvevitotvouzvi
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5433/registration
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: create
