server:
  port: 8093

spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/registration
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: create
