server:
  port: 8093
spring:
  profile: local
  mail:
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: update
